version: '3.8'

services:
  
  api:
    image: anusriesto47/data-analyser
    build: 
     context: .
     dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - .env
    restart: unless-stopped