name: rust_analyser_web_deployment

on:
   push:
      branches:
         - main

jobs:
   build:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Enable BuildKit
         run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

       - name: Install Rust
         uses: dtolnay/rust-toolchain@stable
         with: 
           toolchain: stable

       - name: Build and test code
         run: |
            cargo build --verbose
            cargo test --verbose

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2

       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build and push Docker image
         uses: docker/build-push-action@v5
         with:
           context: .  # Change this if your Dockerfile is in a subfolder
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/rust_analyser:latest

   deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
       - name: Checkout code
         uses: actions/checkout@v3 

       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Install sshpass
         run: sudo apt-get install -y sshpass

       - name: Copy docker-compose.yml to droplet
         run: sshpass -p "${{ secrets.DROPLET_PASSWORD }}" scp -o StrictHostKeyChecking=no docker-compose.yml root@${{ vars.DROPLET_IP }}:~

       - name: Deploy
         uses: appleboy/ssh-action@master
         with:
           host: ${{ vars.DROPLET_IP }}
           username: root
           password: ${{ secrets.DROPLET_PASSWORD }}
           script: |
             cd ~
             export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
             docker-compose down
             docker-compose pull
             docker-compose up -d
